project_id = "mhhskwckcxoeqtkeduoz"

[functions.fetch-lender-details]
verify_jwt = false

[functions.debt-advisor]
verify_jwt = false

[functions.categorize-expense]
verify_jwt = false

[functions.auto-backup]
verify_jwt = false

[functions.sync-changes]
verify_jwt = false
